# Generated by Django 4.2.7 on 2023-11-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('created', 'Создан'), ('published', 'Опубликован')], default='created', max_length=20)),
            ],
        ),
    ]
